export default [
  {
    login: 'mathewtrivett',
    id: 1696963,
    node_id: 'MDQ6VXNlcjE2OTY5NjM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1696963?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mathewtrivett',
    html_url: 'https://github.com/mathewtrivett',
    followers_url: 'https://api.github.com/users/mathewtrivett/followers',
    following_url:
      'https://api.github.com/users/mathewtrivett/following{/other_user}',
    gists_url: 'https://api.github.com/users/mathewtrivett/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/mathewtrivett/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/mathewtrivett/subscriptions',
    organizations_url: 'https://api.github.com/users/mathewtrivett/orgs',
    repos_url: 'https://api.github.com/users/mathewtrivett/repos',
    events_url: 'https://api.github.com/users/mathewtrivett/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/mathewtrivett/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'tiredoak',
    id: 4021101,
    node_id: 'MDQ6VXNlcjQwMjExMDE=',
    avatar_url: 'https://avatars.githubusercontent.com/u/4021101?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/tiredoak',
    html_url: 'https://github.com/tiredoak',
    followers_url: 'https://api.github.com/users/tiredoak/followers',
    following_url:
      'https://api.github.com/users/tiredoak/following{/other_user}',
    gists_url: 'https://api.github.com/users/tiredoak/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/tiredoak/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/tiredoak/subscriptions',
    organizations_url: 'https://api.github.com/users/tiredoak/orgs',
    repos_url: 'https://api.github.com/users/tiredoak/repos',
    events_url: 'https://api.github.com/users/tiredoak/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/tiredoak/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'HJEGeorge',
    id: 28685265,
    node_id: 'MDQ6VXNlcjI4Njg1MjY1',
    avatar_url: 'https://avatars.githubusercontent.com/u/28685265?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/HJEGeorge',
    html_url: 'https://github.com/HJEGeorge',
    followers_url: 'https://api.github.com/users/HJEGeorge/followers',
    following_url:
      'https://api.github.com/users/HJEGeorge/following{/other_user}',
    gists_url: 'https://api.github.com/users/HJEGeorge/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/HJEGeorge/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/HJEGeorge/subscriptions',
    organizations_url: 'https://api.github.com/users/HJEGeorge/orgs',
    repos_url: 'https://api.github.com/users/HJEGeorge/repos',
    events_url: 'https://api.github.com/users/HJEGeorge/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/HJEGeorge/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'janechuk',
    id: 35715430,
    node_id: 'MDQ6VXNlcjM1NzE1NDMw',
    avatar_url: 'https://avatars.githubusercontent.com/u/35715430?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/janechuk',
    html_url: 'https://github.com/janechuk',
    followers_url: 'https://api.github.com/users/janechuk/followers',
    following_url:
      'https://api.github.com/users/janechuk/following{/other_user}',
    gists_url: 'https://api.github.com/users/janechuk/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/janechuk/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/janechuk/subscriptions',
    organizations_url: 'https://api.github.com/users/janechuk/orgs',
    repos_url: 'https://api.github.com/users/janechuk/repos',
    events_url: 'https://api.github.com/users/janechuk/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/janechuk/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'pmhofmann',
    id: 43821350,
    node_id: 'MDQ6VXNlcjQzODIxMzUw',
    avatar_url: 'https://avatars.githubusercontent.com/u/43821350?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/pmhofmann',
    html_url: 'https://github.com/pmhofmann',
    followers_url: 'https://api.github.com/users/pmhofmann/followers',
    following_url:
      'https://api.github.com/users/pmhofmann/following{/other_user}',
    gists_url: 'https://api.github.com/users/pmhofmann/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/pmhofmann/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/pmhofmann/subscriptions',
    organizations_url: 'https://api.github.com/users/pmhofmann/orgs',
    repos_url: 'https://api.github.com/users/pmhofmann/repos',
    events_url: 'https://api.github.com/users/pmhofmann/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/pmhofmann/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Dwake5',
    id: 45290034,
    node_id: 'MDQ6VXNlcjQ1MjkwMDM0',
    avatar_url: 'https://avatars.githubusercontent.com/u/45290034?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Dwake5',
    html_url: 'https://github.com/Dwake5',
    followers_url: 'https://api.github.com/users/Dwake5/followers',
    following_url: 'https://api.github.com/users/Dwake5/following{/other_user}',
    gists_url: 'https://api.github.com/users/Dwake5/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Dwake5/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Dwake5/subscriptions',
    organizations_url: 'https://api.github.com/users/Dwake5/orgs',
    repos_url: 'https://api.github.com/users/Dwake5/repos',
    events_url: 'https://api.github.com/users/Dwake5/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Dwake5/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'drinobre',
    id: 71460664,
    node_id: 'MDQ6VXNlcjcxNDYwNjY0',
    avatar_url: 'https://avatars.githubusercontent.com/u/71460664?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/drinobre',
    html_url: 'https://github.com/drinobre',
    followers_url: 'https://api.github.com/users/drinobre/followers',
    following_url:
      'https://api.github.com/users/drinobre/following{/other_user}',
    gists_url: 'https://api.github.com/users/drinobre/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/drinobre/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/drinobre/subscriptions',
    organizations_url: 'https://api.github.com/users/drinobre/orgs',
    repos_url: 'https://api.github.com/users/drinobre/repos',
    events_url: 'https://api.github.com/users/drinobre/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/drinobre/received_events',
    type: 'User',
    site_admin: false,
  },
];
