export default {
  login: 'tiredoak',
  id: 4021101,
  node_id: 'MDQ6VXNlcjQwMjExMDE=',
  avatar_url: 'https://avatars.githubusercontent.com/u/4021101?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/tiredoak',
  html_url: 'https://github.com/tiredoak',
  followers_url: 'https://api.github.com/users/tiredoak/followers',
  following_url: 'https://api.github.com/users/tiredoak/following{/other_user}',
  gists_url: 'https://api.github.com/users/tiredoak/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/tiredoak/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/tiredoak/subscriptions',
  organizations_url: 'https://api.github.com/users/tiredoak/orgs',
  repos_url: 'https://api.github.com/users/tiredoak/repos',
  events_url: 'https://api.github.com/users/tiredoak/events{/privacy}',
  received_events_url: 'https://api.github.com/users/tiredoak/received_events',
  type: 'User',
  site_admin: false,
  name: null,
  company: null,
  blog: '',
  location: 'London',
  email: null,
  hireable: null,
  bio: 'Data Engineer',
  twitter_username: null,
  public_repos: 18,
  public_gists: 10,
  followers: 0,
  following: 1,
  created_at: '2013-03-31T19:19:20Z',
  updated_at: '2022-02-18T17:06:18Z',
};
