export default {
  login: 'francosta',
  id: 46807757,
  node_id: 'MDQ6VXNlcjQ2ODA3NzU3',
  avatar_url: 'https://avatars.githubusercontent.com/u/46807757?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/francosta',
  html_url: 'https://github.com/francosta',
  followers_url: 'https://api.github.com/users/francosta/followers',
  following_url:
    'https://api.github.com/users/francosta/following{/other_user}',
  gists_url: 'https://api.github.com/users/francosta/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/francosta/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/francosta/subscriptions',
  organizations_url: 'https://api.github.com/users/francosta/orgs',
  repos_url: 'https://api.github.com/users/francosta/repos',
  events_url: 'https://api.github.com/users/francosta/events{/privacy}',
  received_events_url: 'https://api.github.com/users/francosta/received_events',
  type: 'User',
  site_admin: false,
  name: 'Francisco',
  company: 'Fika',
  blog: '',
  location: 'Lisbon, Portugal',
  email: null,
  hireable: true,
  bio: null,
  twitter_username: null,
  public_repos: 251,
  public_gists: 0,
  followers: 7,
  following: 1,
  created_at: '2019-01-18T06:41:09Z',
  updated_at: '2022-04-09T18:15:06Z',
};
